# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ze9IIjHbiJXlvLOXK4_5InHSiWb8YSoo
"""

print("Tes")